version: '3'
services:
  puzzle:
    build: .
    depends_on:
      -  puzzledb
  puzzledb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nQueensPuzzle
      - POSTGRES_PASSWORD=nQueensPuzzle
      - POSTGRES_DB=nQueensPuzzle
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

